import { getDatabase } from "@netlify/database";
import type { Config, Context } from "@netlify/functions";
import crypto from "node:crypto";
const db=getDatabase(), J=(x:any,s=200)=>Response.json(x,{status:s});
const sec=()=>Netlify.env.get("ADMIN_PASSWORD")||"";
const sig=(v:string)=>crypto.createHmac("sha256",sec()).update(v).digest("hex");
const okAdmin=(r:Request)=>(r.headers.get("authorization")||"")==="Bearer "+sig("wonderland-admin")&&!!sec();
export default async(r:Request,c:Context)=>{try{
 const path=new URL(r.url).pathname.replace(/^\/api\//,""),a=path.split("/").filter(Boolean);
 if(path==="admin/login"&&r.method==="POST"){const b:any=await r.json();if(!sec())return J({error:"관리자 비밀번호가 아직 설정되지 않았습니다."},503);if(b.password!==sec())return J({error:"비밀번호가 맞지 않습니다."},401);return J({token:sig("wonderland-admin")})}
 if(a[0]==="admin"&&!okAdmin(r))return J({error:"관리자 로그인이 필요합니다."},401);
 if(path==="admin/polls"&&r.method==="GET"){const rows=await db.sql`SELECT p.*,COUNT(r.id)::int responses FROM polls p LEFT JOIN responses r ON r.poll_id=p.id GROUP BY p.id ORDER BY p.created_at DESC`;return J({polls:rows})}
 if(path==="admin/polls"&&r.method==="POST"){const b:any=await r.json();if(!b.title?.trim()||!Array.isArray(b.options)||b.options.length<2)return J({error:"제목과 선택지 2개 이상을 입력해 주세요."},400);const pid=crypto.randomUUID().slice(0,8);await db.sql`INSERT INTO polls(id,title,description,mode,deadline) VALUES(${pid},${b.title.trim()},${b.description||""},${b.mode==="multiple"?"multiple":"single"},${b.deadline||null})`;for(let i=0;i<b.options.length;i++){const oid=crypto.randomUUID().slice(0,12);await db.sql`INSERT INTO poll_options(id,poll_id,label,position) VALUES(${oid},${pid},${b.options[i]},${i})`}return J({id:pid},201)}
 if(a[0]==="admin"&&a[1]==="polls"&&a[2]&&r.method==="GET"){const pid=a[2];const [poll]=await db.sql`SELECT * FROM polls WHERE id=${pid}`;if(!poll)return J({error:"Poll을 찾을 수 없습니다."},404);const rows=await db.sql`SELECT o.id,o.label,COUNT(ra.response_id)::int count FROM poll_options o LEFT JOIN response_answers ra ON ra.option_id=o.id WHERE o.poll_id=${pid} GROUP BY o.id,o.label,o.position ORDER BY o.position`;const [t]=await db.sql`SELECT COUNT(*)::int total FROM responses WHERE poll_id=${pid}`;const total=(t as any).total;return J({poll,total,results:rows.map((x:any)=>({...x,percent:total?Math.round(x.count*100/total):0}))})}
 if(a[0]==="polls"&&a[1]&&a.length===2&&r.method==="GET"){const pid=a[1];const [poll]:any[]=await db.sql`SELECT id,title,description,mode,deadline,closed FROM polls WHERE id=${pid}`;if(!poll)return J({error:"존재하지 않는 Poll입니다."},404);if(poll.closed||(poll.deadline&&new Date(poll.deadline)<new Date()))return J({error:"마감된 Poll입니다."},410);const options=await db.sql`SELECT id,label FROM poll_options WHERE poll_id=${pid} ORDER BY position`;return J({poll:{...poll,options}})}
 if(a[0]==="polls"&&a[1]&&a[2]==="vote"&&r.method==="POST"){const pid=a[1],b:any=await r.json();if(!Array.isArray(b.answers)||!b.answers.length)return J({error:"선택해 주세요."},400);const [poll]:any[]=await db.sql`SELECT * FROM polls WHERE id=${pid}`;if(!poll||poll.closed||(poll.deadline&&new Date(poll.deadline)<new Date()))return J({error:"응답할 수 없는 Poll입니다."},410);if(poll.mode==="single"&&b.answers.length!==1)return J({error:"하나만 선택해 주세요."},400);const valid:any[]=await db.sql`SELECT id FROM poll_options WHERE poll_id=${pid}`,set=new Set(valid.map(x=>x.id));if(b.answers.some((x:string)=>!set.has(x)))return J({error:"잘못된 선택지입니다."},400);const dh=crypto.createHash("sha256").update(pid+"|"+(r.headers.get("user-agent")||"browser")+"|"+(c.ip||"")).digest("hex"),rid=crypto.randomUUID();try{await db.sql`INSERT INTO responses(id,poll_id,device_hash) VALUES(${rid},${pid},${dh})`}catch{return J({error:"이미 응답한 기기입니다."},409)}for(const oid of [...new Set(b.answers as string[])])await db.sql`INSERT INTO response_answers(response_id,option_id) VALUES(${rid},${oid})`;return J({ok:true},201)}
 return J({error:"Not found"},404)
}catch(e){console.error(e);return J({error:"서버 오류가 발생했습니다."},500)}};
export const config:Config={path:"/api/*"};