ALTER TABLE polls ADD COLUMN IF NOT EXISTS survey_type TEXT NOT NULL DEFAULT 'poll';
ALTER TABLE responses ADD COLUMN IF NOT EXISTS respondent_name TEXT;
ALTER TABLE responses ADD COLUMN IF NOT EXISTS class_name TEXT;
ALTER TABLE responses ADD COLUMN IF NOT EXISTS extra_data JSONB NOT NULL DEFAULT '{}'::jsonb;